skin/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from . import db, bcrypt
from .forms import RegisterForm, LoginForm,UpdateProfileForm
from .models import User,Picture,VisitLog
from flask_login import login_user, logout_user, login_required, current_user,login_manager
import tensorflow as tf
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from tensorflow.keras.metrics import AUC
import numpy as np
import os
from werkzeug.utils import secure_filename  # Correct import
from datetime import datetime

main_bp = Blueprint('main_bp', __name__)

@main_bp.before_request
def log_user_visit():
    if current_user.is_authenticated:
        visit = VisitLog(user_id=current_user.id, visit_time=datetime.utcnow())
        db.session.add(visit)
        db.session.commit()

UPLOAD_FOLDER = 'skin/static/uploads/'
if not os.path.exists(UPLOAD_FOLDER):
    os.makedirs(UPLOAD_FOLDER)

dependencies = {'auc_roc': AUC}
verbose_name = {
    0: 'Actinic keratoses and intraepithelial carcinomae',
    1: 'Basal cell carcinoma',
    2: 'Benign keratosis-like lesions',
    3: 'Dermatofibroma',
    4: 'Melanocytic nevi',
    5: 'Pyogenic granulomas and hemorrhage',
    6: 'Melanoma',
    7: 'Hives',
    8: 'Scabies',
    9: 'Bullous Pemphigoid',
    10: 'Acne/Rosacea',
    11: 'Vascular Tumor',
    12: 'Vasculitis',
    13: 'Pigmentation Disorder',
    14: 'STDs - Herpes/AIDS'
}

def get_recommendation(predict_result):
    recommendation_is = "Cannot recommend"
    related_article = "#"
    recommended_products = ""

    if "Basal cell" in predict_result:
        recommendation_is = "Electrodesiccation and curettage (EDC)"
        related_article = "https://www.aad.org/public/diseases/skin-cancer/types/basal-cell-carcinoma"
        recommended_products = "EDC kits"
    elif "Actinic" in predict_result:
        recommendation_is = "Liquid Nitrogen Cryosurgery"
        related_article = "https://www.aad.org/public/diseases/skin-cancer/types/actinic-keratosis"
        recommended_products = "Cryosurgery equipment"
    elif "keratosis" in predict_result:
        recommendation_is = "Phototherapy"
        related_article = "https://www.mayoclinic.org/diseases-conditions/actinic-keratosis/diagnosis-treatment/drc-20379564"
        recommended_products = "Phototherapy devices"
    elif "Dermatofibroma" in predict_result:
        recommendation_is = "Surgical shaving of top"
        related_article = "https://www.mayoclinic.org/diseases-conditions/dermatofibroma/diagnosis-treatment/drc-20355824"
        recommended_products = "Surgical tools"
    elif "nevi" in predict_result:
        recommendation_is = "Surgical removal for cosmetic consideration"
        related_article = "https://www.aad.org/public/diseases/skin-cancer/types/melanocytic-nevi"
        recommended_products = "Surgical removal products"
    elif "Melanoma" in predict_result:
        recommendation_is = "Surgery"
        related_article = "https://www.cancer.org/cancer/melanoma-skin-cancer/treating/surgery.html"
        recommended_products = "Surgical kits"
    elif "hemorrhage" in predict_result:
        recommendation_is = "Electrocautery"
        related_article = "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2797321/"
        recommended_products = "Electrocautery equipment"
    elif "pyogenic granulomas" in predict_result:
        recommendation_is = "Laser therapy"
        related_article = "https://www.aad.org/public/diseases/a-z/pyogenic-granuloma"
        recommended_products = "Laser therapy devices"
    elif "acne" in predict_result:
        recommendation_is = "Topical treatments"
        related_article = "https://www.aad.org/public/diseases/acne"
        recommended_products = "Topical acne treatments"
    elif "Vascular Tumor" in predict_result:
        recommendation_is = "Surgical removal"
        related_article = "https://www.aad.org/public/diseases/skin-cancer/types/vascular-tumor"
        recommended_products = "Surgical removal tools"
    elif "Vasculitis" in predict_result:
        recommendation_is = "Corticosteroids"
        related_article = "https://www.mayoclinic.org/diseases-conditions/vasculitis/diagnosis-treatment/drc-20350873"
        recommended_products = "Corticosteroids"
    elif "Pigmentation Disorder" in predict_result:
        recommendation_is = "Topical treatments"
        related_article = "https://www.aad.org/public/diseases/a-z/hyperpigmentation"
        recommended_products = "Topical treatments"
    elif "STDs" in predict_result:
        recommendation_is = "Antiviral medication"
        related_article = "https://www.cdc.gov/std/treatment/default.htm"
        recommended_products = "Antiviral medications"

    return recommendation_is, related_article, recommended_products


model = load_model('skin/model/dermnet_m2.h5', custom_objects=dependencies)

def predict_label(img_path):
    test_image = image.load_img(img_path, target_size=(28, 28))
    test_image = image.img_to_array(test_image) / 255.0
    test_image = np.expand_dims(test_image, axis=0)

    predict_x = model.predict(test_image)
    classes_x = np.argmax(predict_x, axis=1)

    return verbose_name[classes_x[0]]

@main_bp.route("/")
@main_bp.route("/first")
def first():
    return render_template('first.html')

@main_bp.route("/register", methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        user_to_create = User(username=form.username.data, email=form.email.data, password=form.password1.data)
        db.session.add(user_to_create)
        db.session.commit()
        flash('Congratulations, you are now a registered user!')
        return redirect(url_for('main_bp.login'))
    return render_template('register.html', title='Register', form=form)

@main_bp.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        attempted_user = User.query.filter_by(username=form.username.data).first()
        if attempted_user and attempted_user.check_password_correction(attempted_password=form.password.data):
            login_user(attempted_user)
            flash(f'Success! You are logged in as: {attempted_user.username}', category='success')
            return redirect(url_for('main_bp.index'))
        else:
            flash('Username or password is incorrect', category='danger')
    return render_template('login.html', form=form)

@main_bp.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You have been logged out.", category='info')
    return redirect(url_for('main_bp.login'))

@main_bp.route("/index", methods=['GET', 'POST'])
@login_required
def index():
    if not current_user.is_authenticated:
        return redirect(url_for('main_bp.login'))
    return render_template("index.html")

@main_bp.route("/submit", methods=['POST'])
@login_required
def submit():
    if 'my_image' not in request.files:
        flash('No file part', category='danger')
        return redirect(request.url)

    file = request.files['my_image']

    if file.filename == '':
        flash('No selected file', category='danger')
        return redirect(request.url)

    if file:
        filename = secure_filename(file.filename)
        img_path = os.path.join(UPLOAD_FOLDER, filename)
        file.save(img_path)

        # Save the picture in the database
        picture = Picture(filename=filename, user_id=current_user.id)
        db.session.add(picture)
        db.session.commit()

        predict_result = predict_label(img_path)
    
        recommendation_is, related_article, recommended_products = get_recommendation(predict_result)

        return render_template('prediction.html', 
                            prediction=predict_result, 
                            img_path=img_path, 
                            recommendation_result=recommendation_is,
                            article_link=related_article,
                            products=recommended_products)

    return redirect(url_for('main_bp.dashboard'))

@main_bp.route("/Graph")
def Graph():
    return render_template('Graph.html')

@main_bp.route("/chart")
def chart():
    return render_template('chart.html')

@main_bp.route("/dashboard", methods=['GET', 'POST'])
@login_required
def dashboard():
    user = current_user
    form = UpdateProfileForm(obj=user)
    if form.validate_on_submit():
        user.username = form.username.data
        user.email = form.email.data
        db.session.commit()
        flash('Profile updated successfully!', category='success')
        return redirect(url_for('main_bp.dashboard'))
    
    if request.method == 'POST' and 'my_image' in request.files:
        img = request.files['my_image']
        if img:
            filename = secure_filename(img.filename)
            img_path = os.path.join(UPLOAD_FOLDER, filename)
            img.save(img_path)

            picture = Picture(filename=filename, user_id=user.id)
            db.session.add(picture)
            db.session.commit()

            flash('Picture uploaded successfully!', category='success')

    pictures = Picture.query.filter_by(user_id=user.id).all()
    return render_template('dashboard.html', user=user, pictures=pictures,form=form)

skin/templates/Graph.html
{% extends 'layout.html' %}

{% block content %}
  <section id="hero">
    <div class="hero-container" data-aos="fade-up">      
      <h2>Skin Cancer Prediction</h2>       
    </div>
  </section>
  <section id="portfolio" class="portfolio">
    <div class="container">
      <div class="section-title" data-aos="zoom-in">
        <h3>Skin Cancer <span>Prediction in Deep Learning</span></h3>
        <h2>Graph</h2>       
      </div>
      <center>
        <h3 class="title-a">         
        </h3>
      </center>
      <body>         
        <div class="col-lg-8 mx-auto">                  
          <div><span style="margin-left:100px;color:red"><font size="12">Model Accuracy</font></div>
          </br>
          </br>                
          <center>	    
            <div><img style="margin-left:-70px;width:800px;height:500px;" src="../static/result.png"</div>
          </center>                                                 
        </div>
        <br>
        <br>
        <br>
        <div class="col-lg-8 mx-auto">
          <div><span style="margin-left:100px;color:red"><font size="12">Model Loss</font></div>
          </br>
          </br>                
          <center>	    
            <div><img style="margin-left:-70px;width:800px;height:500px;" src="../static/results.png"</div>
          </center>                                                 
        </div>
      </body>        
    </div>
  </section> 
{% endblock %}

skin/templates/admin_dashboard.html
{% extends "layout.html" %}

{% block content %}
<h1>Admin Dashboard</h1>

<h2>Users</h2>
<ul>
    {% for user in users %}
    <li>
        <a href="{{ url_for('admin_bp.user_detail', user_id=user.id) }}">{{ user.username }}</a> - {{ user.email }} - {{ 'Admin' if user.is_admin else 'User' }}
    </li>
    {% endfor %}
</ul>

<h2>Uploaded Pictures</h2>
<ul>
    {% for picture in pictures %}
    <li>
        <img src="{{ url_for('static', filename='uploads/' ~ picture.filename) }}" alt="Uploaded Image" width="200">
        <p>Uploaded by: {{ picture.user.username }} on {{ picture.upload_date.strftime('%Y-%m-%d %H:%M:%S') }}</p>
    </li>
    {% endfor %}
</ul>

<h2>User Visits</h2>
<p>Total Visits: {{ visit_count }}</p>
<ul>
    {% for visit in visit_logs %}
    <li>
        {{ visit.user.username }} visited at {{ visit.visit_time.strftime('%Y-%m-%d %H:%M:%S') }}
    </li>
    {% endfor %}
</ul>
{% endblock %}

skin/templates/chart.html
{% extends 'layout.html' %}

{% block content %}
  <section id="hero">
    <div class="hero-container" data-aos="fade-up">
      <h2>Skin Cancer Prediction</h2>
    </div>
  </section>

  <section id="portfolio" class="portfolio">
    <div class="container">
      <div class="section-title" data-aos="zoom-in">
        <h3>Skin Cancer <span>Prediction in Deep Learning</span></h3>
        <h2>chart</h2>
      </div>

      <center>
        <h3 class="title-a">
        </h3>
      </center>

      <html>
        <head>
          <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
          <script type="text/javascript">
            google.charts.load("current", {packages:["corechart"]});
            google.charts.setOnLoadCallback(drawChart);
            function drawChart() {
              var data = google.visualization.arrayToDataTable([
                ['class', 'percentage'],
                ['nv ',     30],
                ['mel',    20],
                ['bkl ',     15],
                ['bcc',    15],
                ['akiec ',     10],
                ['vasc',    5],
                ['df',    5]
              ]);

              var options = {
                title: '',
                is3D: true,
              };

              var chart = new google.visualization.PieChart(document.getElementById('piechart_3d'));
              chart.draw(data, options);
            }
          </script>
        </head>
        <body>
          <center><h1>Skin Cancer Detection </h1></center>
          <center><div id="piechart_3d" style="width: 900px; height: 500px; "></div></center>
        </body>
      </html>
    </div>
  </section> 
{% endblock %}

skin/templates/dashboard.html
{% extends 'layout.html' %}

{% block content %}
  <section id="hero">
    <div class="hero-container" data-aos="fade-up">
      <h2>User Dashboard</h2>
    </div>
  </section>

  <section id="dashboard" class="dashboard">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1>Dashboard</h1>
          <p>Welcome, {{ current_user.username }}!</p> 

          <h2>Update Profile</h2>
          <center>
          <form method="POST" action="{{ url_for('main_bp.dashboard') }}">
            {{ form.hidden_tag() }}
              <div>
                  <label for="username">Update Username</label><br>
                  <input type="text" id="username" name="username" placeholder="{{ user.username }}" required>
              </div>
              <br>
              <div>
                  <label for="email">Update Email</label><br>
                  <input type="email" id="email" name="email" placeholder="{{ user.email }}" required>
              </div><br>
              <button type="submit" class="btn btn-primary" name="update_profile">Update Profile</button>
          </form>
          </center>
          <br>
          <h2>Upload a new image</h2>
          <form method="POST" enctype="multipart/form-data">
              <div class="form-group" style="width: 25%; height: 50px;" >
                  <input type="file" name="my_image" class="form-control">
              </div>
              <button type="submit" class="btn btn-primary">Upload</button>
          </form>

          <h2>Your Uploaded Images</h2>
          {% if pictures %}
              <ul>
              {% for picture in pictures %}
                  <li>
                      <img src="{{ url_for('static', filename='uploads/' ~ picture.filename) }}" alt="Uploaded Image" width="200">
                      <p>Uploaded on: {{ picture.upload_date.strftime('%Y-%m-%d %H:%M:%S') }}</p>
                  </li>
              {% endfor %}
              </ul>
          {% else %}
              <p>You have not uploaded any images yet.</p>
          {% endif %}
        </div>
      </div>
    </div>
  </section> 
{% endblock %}

skin/templates/first.html
{% extends 'layout.html' %}

{% block content %}
<section id="hero" style="background-color: #333; color: white; padding: 150px 0;">
  <div class="container" data-aos="fade-up">
    <h1>Transforming Skincare with Artificial Intelligence</h1>
    <center>
    <p style="padding-top: 100px; size: 9cap;">Welcome to our advanced AI-driven platform that revolutionizes skincare diagnosis and treatment recommendations. Powered by cutting-edge machine learning algorithms, we provide accurate and personalized solutions for various skin conditions.</p>
  
    <p><strong>Accurate Diagnosis:</strong> Our AI analyzes skin images with precision, detecting a wide range of dermatological conditions.</p>
    <p><strong>Personalized Recommendations:</strong> Receive tailored skincare routines and product recommendations based on your unique skin profile and condition.</p>
    <p><strong>Continuous Learning:</strong> Our system evolves with new data, ensuring the latest in skincare advancements and treatments.</p>
    
    <p>Join thousands who have already benefited from our technology. Start your journey to healthier, radiant skin today.</p>
  </center>
    <!-- Your existing content -->
  </div>
</section>
{% endblock %}

skin/templates/index.html
{% extends 'layout.html' %}

{% block content %}
<section id="hero">
    <div class="hero-container" data-aos="fade-up">
      <h2>Skin Disease Prediction
      </h2>
    </div>
  </section>

  <section id="portfolio" class="portfolio">
    <div class="container">
      <div class="section-title" data-aos="zoom-in">
        <h3>Skin Disease <span>Prediction in Deep Learning</span></h3>
        <h2>Preview</h2>
      </div>
      <head>
        <script>
   function previewImage() {
       var file = document.getElementById("imagefile").files;
       if (file.length > 0) {
           var fileReader = new FileReader();

           fileReader.onload = function (event) {
               document.getElementById("preview").setAttribute("src", event.target.result);
           };

           fileReader.readAsDataURL(file[0]);
       }
   }
</script>
</head>
<center>
<body>
 <div class="section-header">
   <h2></h2>
  
 </div>
 <nav class="root navbar navbar-default navbar-fixed-top">
   <div class="container-fluid row">
     <div class="navbar-header col-md-1 col-sm-1">
          
     </div>
     
     
   </div>
 </nav>


 <div class="limiter">
   <div class="container-login100" style="background-image: url(../static/images/background1.jpg); background-size: fill;">
     <div class="wrap-login100">
       <div class="login100-form-title" style=" background-image: url(../static/images/background2.jpg);">
    
   
         <span class="login100-form-title-1">
           Upload Image:
         </span>
     
       </div>
   </br>
   </br>
       <form class="login100-form validate-form" action="/submit" method="POST" enctype="multipart/form-data">
         <div class="wrap-input100 validate-input m-b-26" data-validate="Username is required">
     <br>
           <input class="input100" type="file" name="my_image" id="imagefile" class="btn" accept="image/*" onchange="previewImage();"  required>

         </div>
   
   <img id="preview">
         <div class="container-login100-form-btn">
     </br>
     </br>
           <button style="background-color: black;" class="btn btn-primary" type="submit 3"> Submit </button>
         </div>
       </form>
     </div>
   </div>

       </div>
 </div> 

  
</body>
    </div>
  </section>
{% endblock %}

skin/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>AI-Powered Skincare Disease Detection</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="../static/assets/vendor/aos/aos.css" rel="stylesheet">
    <link href="../static/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="../static/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="../static/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="../static/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="../static/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="../static/assets/css/styles.css" rel="stylesheet"> 

</head>
<body>
    {% include 'includes/_navbar.html' %}
    <main id="main">
      <center>
      {% with messages = get_flashed_messages(with_categories=True) %}
    {% if messages %}
        <div class="alert-container" style="width: 75%; height: auto;">
            {% for category, message in messages %}
                <div class="alert alert-{{ category }}" style="font-size: 1.2em; width: 75%; height: auto;">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    {% endif %}
{% endwith %}</center>

        {% block content %}
        {% endblock %} 
    </main>

    <footer id="footer">
        <center>
          <div class="footer-top">
            <div class="container">
            </div>
          </div>
          <div class="container footer-bottom clearfix">
            Contact Us | <a href="#">Privacy Policy</a> | <a href="#">Terms of Service</a>
            <br>
            © 2024 AI Skincare Solutions. All rights reserved.
          </div>
        </center>
      </footer>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="../static/assets/vendor/purecounter/purecounter_vanilla.js"></script>
    <script src="../static/assets/vendor/aos/aos.js"></script>
    <script src="../static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="../static/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="../static/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="../static/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="../static/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="../static/assets/js/main.js"></script>
</body>
</html>

skin/templates/login.html
{% extends 'layout.html' %}

{% block content %}
<section id="hero">
    <div class="hero-container" data-aos="fade-up">      
      <h2>Skin Disease Prediction</h2>       
    </div>
  </section>

    <section id="portfolio" class="portfolio">
      <div class="container">
        <div class="section-title" data-aos="zoom-in">
          <h3>Skin Disease <span>Prediction in Deep Learning</span></h3>
          <h2>Login</h2>         
        </div>
        
        <head>
	
          <script>
         addEventListener("load", function () {
             setTimeout(hideURLbar, 0);
         }, false);
 
         function hideURLbar() {
             window.scrollTo(0, 1);
         }
 
         function login(){
         var uname = document.getElementById("uname").value;
         var pwd = document.getElementById("pwd").value;
 
     if(uname == "admin" && pwd == "admin")
     {
       alert("Login Success!");
       
       window.location = "{{url_for('main_bp.index')}}";
       return false;
     }
     else
     {
     alert("Invalid Credentials!")
     }
         }
         
           
 
 
  
     </script>
     
 </head>
  
  <body id="page-top">
 
    
       
 
   <!-- Portfolio Section -->
   <section class="page-section portfolio" id="portfolio">
  
       
       <!-- Portfolio Section Heading -->
        
       <!-- Icon Divider -->
       <!-- Portfolio Grid Items -->
       <div class="row">
        <div class="section-header">
          <h2></h2>
         
        </div>
        
         <div class="col-md-6 col-lg-4" style="margin-left:390px">
          <center>
          <div class="container">
            <form method="POST" class="form-signin" style="color:white">
                {{ form.hidden_tag() }}
                
                <h1 class="h3 mb-3 font-weight-normal">
                    Please Login
                </h1>
                <br>
                {{ form.username.label() }}
                {{ form.username(class="form-control", placeholder="User Name") }}
        
                {{ form.password.label() }}
                {{ form.password(class="form-control", placeholder="Password") }}
        
                <br>
        
        
                <div class="checkbox mb-3">
                   <h6 style="color: black;">Do not have an account?</h6>
                   <a class="btn btn-sm btn-secondary" href="{{ url_for('main_bp.register') }}">Register</a>
                </div>
        
                {{ form.submit(class="btn btn-lg btn-block btn-primary") }}
        
            </form>
         </div>
                 <br>
                 <br>
                 
                 
                
                 <div class="control-group">
                   <!-- Button -->
                  
                 </div></center>
                  </div>
   </div>
   </div>
  
  
   </section> 
 
     </body>	 		
      </div>
    </section>
{% endblock %}

skin/templates/prediction.html
{% extends 'layout.html' %}

{% block content %}
<section id="hero">
    <div class="hero-container" data-aos="fade-up">      
      <h2>Skin Disease Prediction</h2>       
    </div>
  </section>

    <section id="portfolio" class="portfolio">
      <div class="container">
        <div class="section-title" data-aos="zoom-in">
          <h3>Skin Disease <span>Classification Deep Learning</span></h3>
          <h2>Prediction</h2>         
        </div>
        <div style="margin-left:200px">                  
          <body>          
    <nav class="root navbar navbar-default navbar-fixed-top">
      <div class="container-fluid row">
        <div class="navbar-header col-md-1 col-sm-1">         
        </div>
            </h1></div>    
      </div>
    </nav>
     <div class="content">           
            <div class="col-lg-12">    
                {% if prediction %}
                  <br>
                  <div style="margin-left:70px">
                  <br>
                <br>
                  <center><h2 style="color:red"> Prediction is : <i> {{prediction}} </i></h2></center>
                  <center><h2 style="color:red"> Recommendation : <i> {{recommendation_result}} </i></h2></center>
                  <center><h2 style="color:red"> Here is the related article : <i> <a href="{{article_link}}">Read More </a> </i></h2></center>
                  <center><h2 style="color:red"> Recommended Products :  {{products}}</h2>
                  </center>
                  <br>
                  <center><h2 style="color:red; font-size: 1rem"  > Note: The model is currently in a learning state and its results may still be improving. As such, the results may be inaccurate. Please contact Your Dermatologist for confirmation and further advice before applying any product. <i> </i></h2></center>
                  {% endif %}
                </div>
  
  </body>	 </div>	
  </div>
  </div>
</div>		
      </div>
    </section>
{% endblock %}

skin/templates/register.html
{% extends 'layout.html' %}

{% block content %}
<section id="hero">
    <div class="hero-container" data-aos="fade-up">
      <h2>Skin Disease Prediction</h2>
    </div>
  </section><!-- End Hero -->
  <section id="portfolio" class="portfolio">
    <div class="container">
      <div class="section-title" data-aos="zoom-in">
        <h3>Skin Disease <span>Prediction in Deep Learning</span></h3>
        <h2>Sign Up</h2>
      </div>
      <center>
      <div class="row">
        <div class="col-md-6 offset-md-3">
          
          <form method="POST" class="form-register" style="color: white">
            {{ form.hidden_tag() }}
            <h1 class="h3 mb-3 font-weight-normal", style="color: darkolivegreen;">Please Create your Account</h1>
            <br>
            {{ form.username.label() }}
            {{ form.username(class="form-control", placeholder="Username") }}

            {{ form.email.label() }}
            {{ form.email(class="form-control", placeholder="Email Address") }}

            {{ form.password1.label() }}
            {{ form.password1(class="form-control", placeholder="Password") }}

            {{ form.password2.label() }}
            {{ form.password2(class="form-control", placeholder="Confirm Password") }}
            <br>
            <div class="checkbox mb-3">
              <h6 style="color: black;">Already have an account?</h6>
              <a class="btn btn-sm btn-secondary" href="{{ url_for('main_bp.login') }}">Login</a>
            </div>
            {{ form.submit(class="btn btn-lg btn-block btn-primary") }}
          </form>
        </div>
      </div>
    </center>
    </div>
  </section>
{% endblock %}